Feature login
Lubycon/divid-back pull request #1
Opened 2021-05-09 16:32 UTC by jellyb3ar

## 내용
### 1. 카카오 OAuth 로그인 기능
<img width="321" alt="스크린샷 2021-05-09 오후 10 49 14" src="https://user-images.githubusercontent.com/43192041/117574606-f0126180-b118-11eb-9733-0eca8082408c.png">
- Access Token을 전달받아 카카오 서버에서 사용자 정보를 받아옴 <br>
- jwt Access Token, Refresh Token을 발급 받아 프론트에 토큰 전달 및 Refresh Token DB 저장 <br>
<br>

### 2.  회원 가입
![스크린샷 2021-05-09 오후 11 16 21](https://user-images.githubusercontent.com/43192041/117575408-9449d780-b11c-11eb-8dd3-7a588b78ed24.png)
- 닉네임, 프로필 이모지를 수정 후 저장

### 3. 로그인 후 여행 프로젝트 등록
![스크린샷 2021-05-09 오후 11 28 30](https://user-images.githubusercontent.com/43192041/117576027-32d73800-b11f-11eb-97e9-ecbef685cd6b.png)

## 특별히 봐줬으면 하는 부분
대부분의 행위가 로그인 후에 가능해서 
JwtAuthInterceptor를 통해
- front에서 받은 토큰 확인/재발급을 하는것으로 구현
- 검증과정에서 decode 후 payload에 있는 user id값을 header에 담아 controller에 넘겨주기

로 구현하였는데 이런식으로 하는게 맞는지 궁금합니다.!
## 참고 사항
로그인, 인터셉터까지 연결되어버려서 PR이 커진것 같아요ㅜㅜ 다음부터는 줄이도록 할게요!!😵

2021-05-10 16:01 UTC, yeong-chae requested changes

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/WebConfig.java
> +        log.info("#########INTERCEPTOR##########");
라이브에선 무의미 해보이네유

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/interceptor/JwtAuthInterceptor.java
> +    @Autowired
`@RequiredArgsConstructor`

요게 있어서 `@Autowired`는 생략해도 될 것 같아요!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/interceptor/JwtAuthInterceptor.java
> +        String jwtAccessToken = request.getHeader("jwtAccessToken");
```suggestion
        String jwtAccessToken = request.getHeader(JWT_ACCESS_TOKEN);
```
상수 선언해두는건 어떨까요?

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/interceptor/JwtAuthInterceptor.java
> +        String jwtAccessToken = request.getHeader("jwtAccessToken");
헤더에 들어가는 값은 전부 한 클래스에서 상수로 관리하면 관리가 용이할 것 같아여!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/interceptor/JwtAuthInterceptor.java
> +        if(jwtRefreshToken == null) {
음 여기부터는 코드 정리가 필요해보입니다!
가독성이 많이 떨어지는 것 같아유 조금 더 유의미한 조건문으로 바꾸고 private function으로 빼보는건 어떨까요?

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/Mapping.java
> +    @NotNull
```suggestion
    @Column(name = "user_id", nullable=false)
```
로 하는게 좋을 것 같아여!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/Trip.java
> +    private Date startDate;
요긴 db column type이 어떻게 되나유?

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/Trip.java
> +    public void update(String url){
```suggestion
    public void updateUrl(String url){
```
좀더 명시적인 이름으로 바꾸는건 어떨까요?

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/TripRepository.java
> +    Long findIdbyTripName(@Param("tripName") String tripName, @Param("ownerId") Long ownerId);
엔티티가 아닌 ID로 리턴받는 이유는 어떤건가유?

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/service/TripService.java
> +    public void save(SaveTripRequest saveTripRequest){
```suggestion
	@Transactional
    public void save(SaveTripRequest saveTripRequest){
```

이 필요해보이네유!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/dto/LoginRequest.java
> +    private String email;
`@Nullable`, `@NotNull` !!!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +        Long expiredTime = 1000 * 60L * 60L; // 토큰 유효 시간 (1시간)
요건 전역변수에 있어도 되겠네여!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +                .signWith(SignatureAlgorithm.HS256,SECRET)
굳굳 알고리즘~~!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +        Long expiredTime = 1000 * 60L * 60L * 24L * 30; // 토큰 유효 시간 (30일)
```suggestion
	Long expiredTime = Duration.ofDays(30).toMillis()
```

요렇게도 가능함당!

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +@Service
```suggestion
@Service
@Slf4j
```

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +            e.printStackTrace();
```suggestion
            logger.error(e)
```

2021-05-10 16:01 UTC, yeong-chae commented on ourney/src/main/resources/application.yml
> +  issuer: SYJ_ISSUE
요건 암호화해야합니다!!!! 이대로 노출되면 안돼요!!!!

2021-05-10 20:42 UTC, shinsunyoung reviewed
유진님 첫 PR 넘나 축하드림니다 ~ !! 🎉  코드 잘 봤어요!! 보면서 궁금했던점이나 제안하고 싶었던 점 몇 가지 코멘트로 달았으니 확인해주시면 감사하겠습니다! 🙏

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/.github/CODEOWNERS
> +* @shinsunyoung
무섭님도 코드오너에 넣어주심 될 것 같슴당!!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/build.gradle
> +	implementation group: 'com.squareup.okhttp', name: 'okhttp', version: '2.7.5'
okhttp를 넣으신 이유가 있으실까욥?

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/build.gradle
> +	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.6'
요건 뭐하는 패키지인가욥??

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/common/config/WebConfig.java
> +@EnableWebMvc
`@EnableWebMvc`을 사용하면 Spring Boot의 MVC 설정은 다 사라지고 직접 MVC에 관련된 모든 설정을 직접해야하는 것이라고 알고 있어요!

- 스프링 MVC 확장
    - `@Configuration` + `WebMvcConfigurer`
- 스프링 MVC 재정의
    - `@Configuration` + `@EnableWebMvc`


https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-auto-configuration

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/common/config/WebConfig.java
> +                .excludePathPatterns(INTERCEPTOR_WHITE_LIST);
`addPathPatterns`로 이미 인터셉터 path 패턴을 정의해주셔서, excludePath를 정의하지 않아도 괜찮을 것 같은데, 어떻게 생각하실지 궁금함니다!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/common/dto/SimpleSuccessResponse.java
> +public class SimpleSuccessResponse {
이 객체는 `message`만 가지고 있는 객체인데, 따로 객체로 감싸서 정의해두신 이유가 있으실까요?

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private Date startDate;
```suggestion
    private LocalDate startDate;
```
Date는 가변 타입이기 때문에 자바8부터 추가된 불변 타입 LocalDate를 사용해도 좋을 것 같아용!

https://namocom.tistory.com/673

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +@Data
특별한 이유가 없다면 lombok의 `@Data`는 피하는게 좋슴니다!  참고하시기 좋을 것 같은 링크 첨부합니당!!

https://cheese10yun.github.io/lombok/

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private String tripNm;
마이너한 제안이지만, `tripNm`에서 `Nm`이라는 축약어보다 `Name`으로 풀어써도 좋을 것 같아용!! Nm 자체가 자주 사용하는 축약어는 아니라 보는 사람에 따라 다르게 해석할 수 있을 수 있을 것 같슴미당

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private Date endDate;
```suggestion
    private LocalDate endDate;
```
요기도 마찬가지입니당!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/Mapping.java
> +@NoArgsConstructor
```suggestion
@NoArgsConstructor(access =  AccessLevel.PROTECTED)
```
다른 엔티티에는 다셨는데 요 엔티티에서는 까먹으신 것 같아 서제스천 두림니당

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/TripRepository.java
> +    Long findAllById(@Param("tripName") String tripName, @Param("ownerId") Long ownerId);
메서드 이름만 봤을 때에는 PK를 이용해서 리스트를 가져오는 메서드 이름으로 보여요! 적절하게 수정해도 좋을 것 같슴미다 ㅎㅎ

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/controller/UserController.java
> +    @GetMapping(value="/login")
혹시 로그인 처리하는건데 HTTP Method를 `GET`으로 설정하신 이유가 있으실까유 ??

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/controller/UserController.java
> +    private final JwtUtil jwtUtil;
요건 그냥 볼 때에는 유틸성 클래스인데, 빈으로 주입 받는 방식이 조금 어색해보이는 것 같아용!!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/dto/SignUpRequest.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
DTO에서 기본생성자 접근제어자를 protected로 설정하신 특별한 이유가 있으실까욥?

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/dto/TokenResponse.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
요것도 마찬가지입니다! DTO에서 기본생성자 접근제어자를 protected로 설정하신 특별한 이유가 있으실까욥?

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/entity/User.java
> +    @NotNull
validation 어노테이션을 사용하는 것 보다는 Column 어노테이션의 속성(nullable)을 사용하면 더 좋을 것 같아용

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +        log.info("VALIDATION!!!!===>"+token);
느낌표 네개가 강렬하네요 ㅋㅋㅋㅋㅌㅋ validation!!!!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +    public Map<String, Object> validate(String token, int type) { // 1: refresh , 0 : access
1: refresh , 0 : access처럼 주석을 사용하는 것 보다는, ENUM을 활용해도 좋을 것 같아용!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/JwtUtil.java
> +           // System.out.println(jws);
주석코드는 나중에 쓰레기 코드가 될 가능성이 높기 때문에 삭제하는게 좋슴니다!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +    @Autowired
지금 빈 주입 방식으로 두 가지 방법을 사용하시는 것 같은데,
1. Field Dependency Injection (`@Autowired`)
2. Constructor Dependency Injection (`@RequiredArgsConstructor`)


특별한 이유가 없으시면 한 방법으로 통일해서 사용하셔도 좋을 것 같아용!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +        if (!userRepository.findByEmail(request.getEmail()).isEmpty()) { // 이미 가입된 회원 -> 바로 토큰 전달
`findByEmail()`은 반환값이 Optional인데, Optional에서 제공해주는 메서드를 사용해보셔도 좋을 것 같아용 ㅎㅎ (다른 코드에서 쓰신 `orElseThrow`처럼욥!) 이미 읽으셨을수도 있지만, 제가 재미있게 읽었던 Optional 관련 아티클 몇 개 올려봄니당@@!!

[자바8 Optional 1부: 빠져나올 수 없는 null 처리의 늪](https://www.daleseo.com/java8-optional-before/)
[자바8 Optional 2부: null을 대하는 새로운 방법](https://www.daleseo.com/java8-optional-after/)
[자바8 Optional 3부: Optional을 Optional답게](https://www.daleseo.com/java8-optional-effective/)

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +        else { // 신규 회원 가입 -> 입력 값 저장 후 토큰 전달
이미 가입된 회원, 신규 회원 가입 메서드 분리를 하면 훨씬 가독성이 좋아질 것 같아유 !!

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +        Long   kakaoId = 0L;
```suggestion
        Long kakaoId = 0L;
```
증맬 마이너한 서제스천임니다 ... ㅎㅎ

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +        String nickname = "";
```suggestion
        String nickName = "";
```

2021-05-10 20:42 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/user/service/UserService.java
> +        String img[] = {"mouse","dog","cat","bear","rabbit"}; // profile 이미지 랜덤
```suggestion
        String[] img = {"mouse","dog","cat","bear","rabbit"}; // profile 이미지 랜덤
```
자바에서는 배열을 선언할 때 자료형 옆에 선언하는게 관습이에용! 그리구 복수를 나타내는 변수이기 때문에 images 같은 변수명도 고려해봄직하네욥!

2021-05-11 06:25 UTC, yeong-chae commented on ourney/src/main/java/com/lubycon/ourney/common/config/WebConfig.java
> +@EnableWebMvc
오호 하나 배워감니다

2021-05-12 11:23 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/Trip.java
> +    private Date startDate;
DATE요!!

2021-05-12 11:39 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/entity/TripRepository.java
> +    Long findIdbyTripName(@Param("tripName") String tripName, @Param("ownerId") Long ownerId);
USER - TRIP 연결해주는 MAPPING 테이블에 insert할 때 바로 Id값만 받아서 넣어주려고 ID만 리턴했습니다!

2021-05-12 14:16 UTC, jellyb3ar commented on ourney/build.gradle
> +	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.5.6'
이거 쿼리 로그 찍을 때 값을 넣어서 보여주는 패키지 입니당!!

2021-05-12 14:18 UTC, jellyb3ar commented on ourney/build.gradle
> +	implementation group: 'com.squareup.okhttp', name: 'okhttp', version: '2.7.5'
앗 빼야되는데 놓친것 같아요! 감사합니당!!

2021-05-12 14:36 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/common/config/WebConfig.java
> +                .excludePathPatterns(INTERCEPTOR_WHITE_LIST);
아아 둘중 하나만 있어도 되겠네요..!! 그렇게 하는 방향으로 수정해보겠습니다 ㅎㅎ

2021-05-12 14:37 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/common/config/interceptor/JwtAuthInterceptor.java
> +        if(jwtRefreshToken == null) {
넵 다시 한번 생각해볼게요!!

2021-05-12 15:14 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private Date startDate;
아 요기는 여행일정이라 나중에 수정도 할수 있게 할라고욤!! 여행 경비 내역 입력시에는 LocalDate로 꼭 써야겠어요!!

2021-05-12 15:24 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/domains/user/controller/UserController.java
> +    @GetMapping(value="/login")
정보를 가져오는거라 GET으로 생각하구 했었어요!! 선영님 코멘트 보구 한번 찾아봤는데 여러모로 POST가 더 나은 것 같네욤!!🤨

2021-05-12 15:26 UTC, shinsunyoung commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private Date startDate;
음음 여행 일정 자체를 수정할 수 있어도 요 객체가 요청 DTO이기 때문에 LocalDate를 써도 괜찮을 것 같아용!

2021-05-12 15:30 UTC, jellyb3ar commented on ourney/src/main/java/com/lubycon/ourney/domains/trip/dto/SaveTripRequest.java
> +    private Date startDate;
아하!!!@@ 네 그렇게 해볼게여 감사합니당!

2021-05-15 15:30 UTC, closed without merging